#!/usr/bin/env Rscript
# Generates LaTeX value macros for the TVCG revision, so that numbers reported in the
# manuscript are written by the analysis pipeline rather than typed by hand.
# Outputs:
#   results_revision/revision_values.tex        - \newcommand macros (\rv...)
#   results_revision/revision_table_tolerance.tex - body rows of Table I (tab:tolerance)
# Sources: the machine-readable outputs in results_revision/ plus two fast refits of the
# primary linear mixed model. Values not derivable from a saved CSV are computed here;
# nothing in this file is transcribed from the manuscript.

suppressPackageStartupMessages({
  library(dplyr)
  library(lme4)
  library(lmerTest)
})

base <- "/Users/bart/Library/CloudStorage/OneDrive-Personal/Documents/R/PawelPerkowskiProject_6dofCorrelations"
res  <- file.path(base, "results_revision")
adf  <- readRDS(file.path(res, "analysis_df_revision.rds"))

macros <- c()
put <- function(name, value) macros[[name]] <<- value
fmt <- function(x, d = 2) formatC(x, format = "f", digits = d)
fmtp <- function(x, d = 3) sub("^0\\.", ".", formatC(x, format = "f", digits = d))

## ---- primary signed-error LMM (published full-covariance fit) ----------------
m_full <- lmer(signedError_m ~ stimulusDisparity_m + soundType +
                 (1 + stimulusDisparity_m | participantId), data = adf, REML = TRUE)
sm <- summary(m_full)$coefficients["stimulusDisparity_m", ]
ci <- confint(m_full, parm = "stimulusDisparity_m", method = "Wald")
put("rvPrimarySlope",    fmt(sm["Estimate"], 3))
put("rvPrimarySlopeSE",  fmt(sm["Std. Error"], 3))
put("rvPrimarySlopeT",   fmt(sm["t value"], 2))
put("rvPrimarySlopeDf",  fmt(sm["df"], 1))
put("rvPrimarySlopeCiLo", fmt(ci[1], 2))
put("rvPrimarySlopeCiHi", fmt(ci[2], 2))
put("rvPrimaryCmPerTen", fmt(10 * sm["Estimate"], 2))
# random-slope LRT (intercept-only vs slopes), ML
m_int  <- lmer(signedError_m ~ stimulusDisparity_m + soundType + (1 | participantId),
               data = adf, REML = FALSE)
m_slp  <- update(m_full, REML = FALSE)
lrt <- anova(m_int, m_slp)
put("rvRandSlopeLrtChi", fmt(lrt$Chisq[2], 2))
put("rvRandSlopeLrtP",   fmtp(lrt[["Pr(>Chisq)"]][2], 3))

## ---- slope-only fit feeding the tolerance table ------------------------------
m_slim <- lmer(signedError_m ~ stimulusDisparity_m + soundType +
                 (0 + stimulusDisparity_m | participantId), data = adf, REML = TRUE)
ss <- summary(m_slim)$coefficients["stimulusDisparity_m", ]
cs <- confint(m_slim, parm = "stimulusDisparity_m", method = "profile", quiet = TRUE)
put("rvTolSlopeCmPerTen", fmt(10 * ss["Estimate"], 2))
put("rvTolSlopeCiLo",     fmt(10 * cs[1], 2))
put("rvTolSlopeCiHi",     fmt(10 * cs[2], 2))
put("rvTolSlopeSd",       fmt(sqrt(unlist(VarCorr(m_slim))[1]), 3))

## ---- tolerance lookup table --------------------------------------------------
tol <- read.csv(file.path(res, "tolerance_lookup_nominal.csv"), comment.char = "#")
row_at <- function(d) tol[tol$disparity_cm == d, ]
dn <- c("15" = "Fifteen", "30" = "Thirty", "70" = "Seventy")
for (d in c(15, 30, 70)) {
  r <- row_at(d); w <- dn[[as.character(d)]]
  put(paste0("rvTolAvgAt", w),   fmt(r$displacement_avg_cm, 1))
  put(paste0("rvTolAvgLoAt", w), fmt(r$displacement_avg_lo_cm, 1))
  put(paste0("rvTolAvgHiAt", w), fmt(r$displacement_avg_hi_cm, 1))
}
put("rvTolPTenAtFifteen",     fmt(row_at(15)$displacement_p10_cm, 1))
put("rvTolPNinetyAtFifteen",  fmt(row_at(15)$displacement_p90_cm, 1))
put("rvTolPTenAtSeventy",     fmt(row_at(70)$displacement_p10_cm, 1))
put("rvTolPNinetyAtSeventy",  fmt(row_at(70)$displacement_p90_cm, 1))
# table body rows: offset & angular & displacement [CI] & traversed
rows <- tol %>%
  filter(disparity_cm %in% c(15, 20, 30, 40, 50, 60, 70)) %>%
  mutate(line = sprintf("%d & %.0f & %.1f \\; [%.1f, %.1f] & %.1f \\\\",
                        disparity_cm, ang_median_deg,
                        displacement_avg_cm, displacement_avg_lo_cm,
                        displacement_avg_hi_cm, traversed_avg_pct))
writeLines(c("% generated by rscripts/revision/generate_revision_values.R - do not edit by hand",
             rows$line),
           file.path(res, "revision_table_tolerance.tex"))
put("rvToleranceRows", paste(rows$line, collapse = " "))

## ---- accuracy model (glmmTMB refit outputs) ----------------------------------
fx <- read.csv(file.path(res, "accuracy_gamma_glmm_fixed_effects.csv"))
jt <- read.csv(file.path(res, "accuracy_gamma_glmm_joint_tests.csv"))
st <- jt[jt$model.term == "soundType", ]
put("rvSoundTypeChi", fmt(st$Chisq, 2))
put("rvSoundTypeP",   fmtp(st$p.value, 3))
tr <- fx[fx$term == "trialSequence_c", ]
put("rvLearnBeta",  fmt(tr$estimate, 4))
put("rvLearnSE",    fmt(tr$se, 4))
put("rvLearnZ",     fmt(tr$z, 2))
put("rvLearnCiLo",  fmt(tr$ci_low, 4))
put("rvLearnCiHi",  fmt(tr$ci_high, 4))
put("rvLearnPctPerTrial", fmt(100 * (1 - exp(tr$estimate)), 2))
put("rvLearnCumPct",      fmt(100 * (1 - exp(23 * tr$estimate)), 0))

## ---- listening distances -----------------------------------------------------
ld <- read.csv(file.path(res, "descriptives_listening_distance.csv"))
d1 <- ld[grepl("all samples", ld$measure), ][1, ]
put("rvDistMedianM", fmt(d1$median, 2))
put("rvDistMeanM",   fmt(d1$mean, 2))
traj <- readRDS(file.path(res, "trajectory_samples_angular.rds"))
put("rvPctUnderHalfM",  fmt(100 * mean(traj$dist_source_m < 0.5), 1))
put("rvPctUnderNfeM",   fmt(100 * mean(traj$dist_source_m < 0.574), 1))
tr10 <- traj %>% group_by(participantId, trialSequenceNum) %>%
  summarise(n_in = sum(dist_source_m < 0.10), .groups = "drop")
put("rvPctTrialsMuteZone", fmt(100 * mean(tr10$n_in > 0), 1))
put("rvMuteDwellS", fmt(median(tr10$n_in[tr10$n_in > 0]) * 0.111, 1))

## ---- write the macro file ----------------------------------------------------
hdr <- c("% revision_values.tex - generated by rscripts/revision/generate_revision_values.R",
         "% Regenerate with: Rscript rscripts/revision/generate_revision_values.R",
         "% Do not edit by hand; edit the generating script instead.")
body <- vapply(names(macros),
               function(n) sprintf("\\newcommand{\\%s}{%s}", n, macros[[n]]),
               character(1))
writeLines(c(hdr, body), file.path(res, "revision_values.tex"))
# keep the submission folder self-contained
for (f in c("revision_values.tex", "revision_table_tolerance.tex"))
  file.copy(file.path(res, f), file.path(base, "IEEE_TVCG", f), overwrite = TRUE)
cat(sprintf("wrote %d macros to %s\n", length(macros), file.path(res, "revision_values.tex")))
